GET https://localhost:7244/login?returnUrl=https%3A%2F%2Flocalhost%3A7244%2Fconnect%2Fauthorization%3Fclient_id%3Dservice-auth%26redirect_uri%3Dhttps%3A%2F%2Flocalhost%3A7244%2Fcallback%26response_type%3Dcode%26code_challenge%3Dtoto%26scope%3Dopenid%20profile

### Set Cookie
@cookie = CfDJ8FXaQUeV1ChIsWYG-EddCLZg5E6GtupkwwTkZLmDpPRZSGsWTZug_oG9BMBW2mnLN5NLnWguoP_fpST_ugRaeYqBnwpMC8iuIMD9lSZbr2yCT58tMT-Z9albGdamofiNZVhOeskQ-h0NnIMyabeAZv_O6zE5MvWQqQVwyI32FlPe1zJBZ3tJcH6PKlv7N3U4vH1PnBzzaksozI1qRkffkUZVdC1ng_XafC3zwkZeH_xPkET9wK7-gOloEFqLKxh-lwIbcSSA8nR0vmkV7A7zBJn8BzzlYJmD8prbBWLU8uk9-rGGPn1lPgrjALR5cmG9_S7aRE3JkFJoAcq_ZI7nHNeMNgcR0n7Ho2P2rb55OeLaywZoEW6Br1lwpR15Qb0vOZFltZYxiT39eNI7Ng2o5ctSSUtwqnMmNVUWBNR8hQoN_WLTRc-cAfNzzqc3bmksc1gHke9HgoDwYxp7zzT55Wo_JOUvuEtlT-UT_sSxWIu4HAoQU9SSPaWv8hMHTjlymr5PzmJDxgPFpDFVLuZZvz6xCv4eGMB3Y0AR5QWqHxcXvMRv4djlpERbZhpHOXju7aspyhVEzIjeyHYCHGtZgstNQId_JpLNH_SRRySZ90ZNKG8bMnl27xfsJEQ87EAeXA

### Auhtorization
GET https://localhost:7244/connect/authorization
?client_id=service-auth
&redirect_uri=https://localhost:7244/callback
&response_type=code
&code_challenge=toto
&scope=openid profile
Cookie: .AspNetCore.Cookies={{cookie}};

### Set Code
@code = ryJitxKCFitPVj1x4jHg8Oq_mvSgDq6AJDHqBoGvINQ

### Authorization Code
POST https://localhost:7244/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&client_id=service-auth
&client_secret=388D45FA-B36B-4988-BA59-B187D329C207
&code={{code}}
&code_verifier=toto
&redirect_uri=https://localhost:7244/callback

### Credentials
POST https://localhost:7244/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=service-worker
&client_secret=388D45FA-B36B-4988-BA59-B187D329C207

### Set Token
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IkJBOTczMUJGMTRCNEY3NEJEOURFRUE1NUJDRUE0NTg4MjM2MTlDNUMiLCJ4NXQiOiJ1cGN4dnhTMDkwdlozdXBWdk9wRmlDTmhuRnciLCJ0eXAiOiJhdCtqd3QifQ.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MjQ0LyIsImV4cCI6MTc0MTg3ODYyNiwiaWF0IjoxNzQxODc1MDI2LCJqdGkiOiJmYTE2NWYwMi05NDk2LTQwNjItOGIzMS1hNjdmZTY4YWI1YTMiLCJzdWIiOiJzZXJ2aWNlLXdvcmtlciIsIm9pX3Byc3QiOiJzZXJ2aWNlLXdvcmtlciIsImNsaWVudF9pZCI6InNlcnZpY2Utd29ya2VyIiwib2lfdGtuX2lkIjoiMTY4ZDQ4MjEtYjkzYS00YzkzLTkzZGUtODE0NDdlNDZjYzE5In0.ab3UeaGzPSaIVNqEjWQRAOVvnN1MeaNXTgXWwtH5NjBYUeNGK9IrDvP_E4RNed9rqdyjj1oc5_nyQIq5Z9Xb_Nujnpunx5g-h88ygftWJ8xfocwWB_CgdiRuXq8xkhm73ZzSrJemLV8D67EdZI0gWcsUfEYi26K5XBdwWC9kMlNmIE7GojMHfwNaBwSmSH7CPyBJPM-fgBiLbCzgWZZvQZG7u0XHi3Zx-fErTe6ZUaC9rOE281oUH0USAYWGox3fpLdyxPeQxpbV5VnqisMDeyMUEE3RuaGvLLA3pjBHhEwtg4vyt7RUAnFvT9NoKq0iETgCOVNm9Yl8uRDBomrjjQ

### Create House
POST https://localhost:7244/explorer/houses
Content-Type: application/json

{
  "name": "House 1",
  "description": "House 1 description"
}

### Get Houses
GET https://localhost:7244/explorer/houses
Content-Type: application/json
Authorization: Bearer {{token}}

### Get House by Id
GET https://localhost:7244/explorer/houses/01958073-743d-727d-bfef-92ae7ab9a5f6
Content-Type: application/json
Authorization: Bearer {{token}}

### Update House by Id
POST https://localhost:7244/explorer/houses/01958073-743d-727d-bfef-92ae7ab9a5f6
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "House updated",
  "description": "House description updated"
}

### Delete House by Id
DELETE  https://localhost:7244/explorer/houses/01958073-743d-727d-bfef-92ae7ab9a5f6
Content-Type: application/json
Authorization: Bearer {{token}}

### NOT FOUND
GET https://localhost:7244/explorer/houses/01958073-743d-727d-bfef-92ae7ab9a5f6
Content-Type: application/json
Authorization: Bearer {{token}}

### API
### API Get Houses by Id
GET https://localhost:7244/api/explorer/houses/01958073-743d-727d-bfef-92ae7ab9a5f6
Content-Type: application/json
### API NOT FOUND
GET https://localhost:7244/api/explorer/houses/xxx
Content-Type: application/json
